# Generated by Django 4.2.19 on 2025-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
