# Generated by Django 4.2.20 on 2025-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
