# Generated by Django 5.1.1 on 2025-04-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sizeprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
